routes:
  /rss/:
    template: rss/all
    content_type: text/xml
  /rss/posts/:
    template: rss/posts
    content_type: text/xml
  /rss/status/:
    template: rss/status
    content_type: text/xml
collections:
  /:
    permalink: /post/{slug}/
    template: index
    filter: tags:-status
  /status/:
    permalink: /status/{id}/
    template: index
    filter: tags:status
    data: tag.status
taxonomies:
  tag: /tag/{slug}/
